services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Controller\:
        resource: '../controller/*'
        tags: ["controller"]
        public: true